src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $FirstName;

    #[ORM\Column(type: 'string', length: 255)]
    private $LastName;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    #[ORM\Column(type: 'integer')]
    private $telephone;

    #[ORM\Column(type: 'string', length: 255)]
    private $message;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

src/Controller/ConctactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\BrowserKit\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ConctactController extends AbstractController
{
    #[Route('/contact', name: 'app_contact')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        //On stocque les rendez-vous dans la base de données
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);


        if ($form->isValid() && $form->isSubmitted()) {
            $entityManager->persist($contact);
            $entityManager->flush();
            $this->addFlash('réussit', 'votre rendez est prise en compte');
        }


        return $this->render('conctact/index.html.twig', [
            'controller_name' => 'ConctactController',
            'contact_adress' => $this->getParameter('app.contact.adress'),
            'contact_phone' => $this->getParameter('app.phone.adress'),
            'contact_email' => $this->getParameter('app.email.adress'),
            'form' => $form->createView()
        ]);
    }
}

templates/conctact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ConctactController!
{% endblock %}

{% block body %}
	<main class="c-page__main c-page__main--close">
		<div class="u-text-center u-mt-sm u-mb-sm u-none@md u-none@sm">
			<h1 class="fw-bold">Agence Immobilière de Paris</h1>
			<h2 class="fw-bold">Prise de Rendez-vous</h2>
		</div>
		{{ form_start (form) }}
		<form>

			<div class="m-4">
				{{ form_row (form.firstName, {'class':'form-control'}) }}
			</div>
			<div class="m-4">
				{{ form_row (form.lastName, {'class':'form-control'}) }}
			</div>

			<div class="m-4">
				{{ form_row (form.email, {'class':'form-control'}) }}
			</div>
			<div class="m-4">
				{{ form_row (form.telephone, {'class':'form-control'}) }}
			</div>
			<div class="m-4">
				{{ form_row (form.message, {'class':'form-control'}) }}
			</div>
			<button class="btn btn-primary m-4">Prendre rendez-vous</button>
		</form>


		{{ form_end (form) }}
		<main>

			<footer>
				<div class="container">
					<div class="col-6">
						<h2 class="fw-bold">
							Contact</h2>
						<span class="fw-bold">Email:<span>
								<p>talla.immoblier@gmail.com</p><br>
								<span class="fw-bold">Téléphone:<span>
										<p>0178630713</p><br>
										<span class="fw-bold">Adresse:<span>
												<p>4 square Jouvenet Paris 16ème</p>

											</div>
										</div>
										<div>
											<p class="float-end">
												<a href="#">Retour en haut de la page</a>
											</p>
											<p>&copy; 2020–2022 Company, Inc. &middot;

											</p>
										</div>

									</footer>
								{% endblock %}